"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/AppShell";

export default function ClinicPage() {
  const [data,setData]=useState<any>(null); const [patients,setPatients]=useState<any[]>([]); const [selected,setSelected]=useState("");
  const [email,setEmail]=useState(""); const [role,setRole]=useState("Consultant"); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  async function load(){setLoading(true);try{const [c,p]=await Promise.all([fetch("/api/clinic",{credentials:"include",cache:"no-store"}),fetch("/api/patients",{credentials:"include",cache:"no-store"})]);const cj=await c.json();const pj=await p.json();if(!c.ok)throw new Error(cj.error||"Could not load clinic.");setData(cj);setPatients(pj.patients||[]);}catch(e){setError(e instanceof Error?e.message:"Could not load clinic.")}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function addMember(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const r=await fetch("/api/clinic",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,role})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||"Could not add member.");else{setEmail("");setMessage("Member added.");await load()}setSaving(false)}
  async function portal(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");const r=await fetch("/api/portal/accounts",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientId:selected,password})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||"Could not enable portal access.");else{setMessage(j.created?"Patient portal access created.":"Patient portal access updated.");setPassword("")}setSaving(false)}
  async function memberAction(method:string,id:string,role?:string){const r=await fetch("/api/clinic",{method,credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(method==="PATCH"?{id,role}:{id})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||"Action failed.");else await load()}
  if(loading)return <AppShell><div className="text-sm text-gray-500">Loading clinic…</div></AppShell>;
  if(error&&!data)return <AppShell><div className="rounded-xl bg-white p-4 text-sm text-red-600">{error}</div></AppShell>;
  const canManage=["Owner","Admin"].includes(data?.currentMember?.role);
  return <AppShell><div className="mb-4"><Link href="/dashboard" className="text-xs text-[#c2183a]">← Dashboard</Link><h1 className="mt-1 text-xl font-bold">Clinic</h1><p className="text-sm text-gray-500">Shared workspace, consultant access and patient portal controls.</p></div>
    {error&&<div className="mb-3 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="mb-3 rounded-xl border border-green-200 bg-green-50 p-3 text-sm text-green-700">{message}</div>}
    <section className="rounded-2xl bg-white p-4 border mb-3"><div className="text-lg font-semibold">{data?.clinic?.name}</div><div className="text-xs text-gray-500">Your role: {data?.currentMember?.role} · {data?.members?.length||0} members</div></section>
    {canManage&&<section className="rounded-2xl bg-white p-4 border mb-3"><h2 className="font-semibold">Patient Portal Access</h2><p className="text-xs text-gray-500 mt-1">Create or reset a patient's portal password. Patients only receive read-only access to their own records.</p><form onSubmit={portal} className="mt-3 space-y-2"><select required value={selected} onChange={e=>setSelected(e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-sm"><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name} · {p.phone}</option>)}</select><div className="flex gap-2"><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Portal password (8+ characters)" className="flex-1 rounded-xl border px-3 py-2.5 text-sm"/><button disabled={saving} className="rounded-xl bg-[#140a1f] px-4 py-2.5 text-sm text-white">{saving?"Saving…":"Enable / Reset"}</button></div></form><Link href="/portal/login" target="_blank" className="inline-block mt-3 text-xs text-[#c2183a]">Open patient portal login →</Link></section>}
    {canManage&&<section className="rounded-2xl bg-white p-4 border mb-3"><h2 className="font-semibold">Add existing MedLum user</h2><p className="mt-1 text-xs text-gray-500">The doctor must already have a MedLum account.</p><form onSubmit={addMember} className="mt-3 space-y-2"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="Doctor's MedLum email" className="w-full rounded-xl border px-3 py-2.5 text-sm"/><div className="flex gap-2"><select value={role} onChange={e=>setRole(e.target.value)} className="rounded-xl border px-3 py-2.5 text-sm bg-white"><option>Consultant</option><option>Admin</option><option>Staff</option></select><button disabled={saving} className="flex-1 rounded-xl bg-[#140a1f] px-4 py-2.5 text-sm font-medium text-white">{saving?"Adding…":"Add member"}</button></div></form></section>}
    <section className="rounded-2xl bg-white border overflow-hidden"><div className="px-4 py-3 border-b font-semibold">Clinic members</div><div className="divide-y">{data?.members?.map((m:any)=><div key={m.id} className="p-4 flex items-center justify-between gap-3"><div className="min-w-0"><div className="font-medium truncate">{m.doctor.name}</div><div className="text-xs text-gray-500 truncate">{m.doctor.email}</div></div>{m.role==="Owner"?<span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs">Owner</span>:canManage?<div className="flex gap-2"><select value={m.role} onChange={e=>memberAction("PATCH",m.id,e.target.value)} className="rounded-lg border px-2 py-1.5 text-xs"><option>Admin</option><option>Consultant</option><option>Staff</option></select><button onClick={()=>memberAction("DELETE",m.id)} className="text-xs text-red-600">Remove</button></div>:<span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs">{m.role}</span>}</div>)}</div></section>
  </AppShell>;
}
