"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/AppShell";
import { apiCreateBloodDonor, apiCreateBloodInventory, apiCreateBloodRequest, apiGetBloodBank, apiGetPatients, apiUpdateBloodInventory, apiUpdateBloodRequest } from "@/lib/api";

const groups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
const components = ["Whole Blood", "PRBC", "Platelets", "FFP", "Cryoprecipitate"];

export default function BloodBankPage() {
  const [data, setData] = useState<{inventory:any[]; donors:any[]; requests:any[]}>({inventory:[],donors:[],requests:[]});
  const [patients, setPatients] = useState<any[]>([]);
  const [tab, setTab] = useState("overview");
  const [message, setMessage] = useState("");
  const [inventory, setInventory] = useState({bloodGroup:"A+",component:"PRBC",unitsAvailable:"1",batchNumber:"",expiryDate:"",storageLocation:"",notes:""});
  const [donor, setDonor] = useState({name:"",bloodGroup:"O+",phone:"",donorCode:"",lastDonationDate:"",status:"Eligible",notes:""});
  const [request, setRequest] = useState({patientId:"",bloodGroup:"A+",component:"PRBC",unitsRequested:"1",urgency:"Routine",crossMatchStatus:"Not Started",notes:""});

  async function load() {
    const [blood, pts] = await Promise.all([apiGetBloodBank(), apiGetPatients()]);
    setData(blood); setPatients(pts);
  }
  useEffect(() => { load(); }, []);

  const totals = useMemo(() => ({ available:data.inventory.reduce((s,x)=>s+Number(x.unitsAvailable||0),0), reserved:data.inventory.reduce((s,x)=>s+Number(x.unitsReserved||0),0), urgent:data.requests.filter(x=>x.urgency==="Emergency"&&x.status!=="Fulfilled"&&x.status!=="Cancelled").length }), [data]);
  const matchingInventory = useMemo(() => data.inventory.filter(x=>x.bloodGroup===request.bloodGroup&&x.component===request.component&&Number(x.unitsAvailable)-Number(x.unitsReserved)>0), [data.inventory,request.bloodGroup,request.component]);

  async function addInventory(e:React.FormEvent){e.preventDefault();const r=await apiCreateBloodInventory(inventory);setMessage(r.success?"Blood inventory added.":r.error||"Could not add inventory");if(r.success){setInventory({...inventory,unitsAvailable:"1",batchNumber:"",expiryDate:"",storageLocation:"",notes:""});await load();}}
  async function addDonor(e:React.FormEvent){e.preventDefault();const r=await apiCreateBloodDonor(donor);setMessage(r.success?"Donor added.":r.error||"Could not add donor");if(r.success){setDonor({...donor,name:"",phone:"",donorCode:"",lastDonationDate:"",notes:""});await load();}}
  async function addRequest(e:React.FormEvent){e.preventDefault();const r=await apiCreateBloodRequest(request);setMessage(r.success?"Blood request created.":r.error||"Could not create request");if(r.success){setRequest({...request,patientId:"",unitsRequested:"1",notes:""});await load();}}
  async function fulfil(id:string){const row=data.requests.find(x=>x.id===id);if(!row)return;const batch=data.inventory.find(x=>x.id===row.inventoryId)||data.inventory.find(x=>x.bloodGroup===row.bloodGroup&&x.component===row.component&&Number(x.unitsAvailable)-Number(x.unitsReserved)>=Number(row.unitsRequested));if(!batch){setMessage("No matching free inventory batch is available.");return;}const r=await apiUpdateBloodRequest({id, status:"Fulfilled", inventoryId:batch.id});setMessage(r.success?"Blood request fulfilled and inventory reduced.":r.error||"Could not fulfill request");await load();}
  async function reserve(id:string){const row=data.requests.find(x=>x.id===id);if(!row)return;const batch=matchingInventory.find(x=>x.bloodGroup===row.bloodGroup&&x.component===row.component&&Number(x.unitsAvailable)-Number(x.unitsReserved)>=Number(row.unitsRequested));if(!batch){setMessage("No matching free inventory batch is available.");return;}const r=await apiUpdateBloodRequest({id,status:"Reserved",inventoryId:batch.id});if(r.success) await apiUpdateBloodInventory({id:batch.id,unitsReserved:Number(batch.unitsReserved)+Number(row.unitsRequested)});setMessage(r.success?"Blood request reserved.":r.error||"Could not reserve request");await load();}

  return <AppShell><div className="mb-4"><Link href="/dashboard" className="text-xs text-[#c2183a]">← Dashboard</Link><h1 className="mt-1 text-xl font-semibold">Blood Bank</h1><p className="text-xs text-gray-500">Clinic blood inventory, donor registry and patient blood requests.</p></div>
    {message&&<div className="mb-3 rounded-lg bg-green-50 px-3 py-2 text-sm text-green-700">{message}</div>}
    <div className="grid grid-cols-3 gap-2 mb-4"><div className="bg-white rounded-xl border p-3"><div className="text-[11px] text-gray-500">Available units</div><div className="text-xl font-bold">{totals.available}</div></div><div className="bg-white rounded-xl border p-3"><div className="text-[11px] text-gray-500">Reserved</div><div className="text-xl font-bold">{totals.reserved}</div></div><div className="bg-white rounded-xl border p-3"><div className="text-[11px] text-gray-500">Emergency requests</div><div className="text-xl font-bold">{totals.urgent}</div></div></div>
    <div className="flex gap-2 overflow-x-auto mb-4">{[["overview","Overview"],["inventory","Inventory"],["requests","Requests"],["donors","Donors"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 rounded-lg text-xs whitespace-nowrap ${tab===id?"bg-[#c2183a] text-white":"bg-white border"}`}>{label}</button>)}</div>

    {tab==="overview"&&<div className="space-y-3"><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Blood availability</h2><div className="grid grid-cols-2 gap-2">{groups.map(g=><div key={g} className="rounded-lg border p-2"><div className="font-semibold text-sm">{g}</div><div className="text-xs text-gray-500">{data.inventory.filter(x=>x.bloodGroup===g).reduce((s,x)=>s+Number(x.unitsAvailable||0),0)} units</div></div>)}</div></div><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Open requests</h2>{data.requests.filter(x=>x.status!=="Fulfilled"&&x.status!=="Cancelled").slice(0,8).map(x=><div key={x.id} className="py-2 border-b last:border-0"><div className="flex justify-between gap-2"><span className="font-medium text-sm">{x.patient?.name||"Patient"}</span><span className="text-xs">{x.bloodGroup} · {x.component}</span></div><div className="text-xs text-gray-500">{x.unitsRequested} unit(s) · {x.urgency} · {x.status}</div></div>)}{data.requests.filter(x=>x.status!=="Fulfilled"&&x.status!=="Cancelled").length===0&&<p className="text-xs text-gray-400">No open requests.</p>}</div></div>}

    {tab==="inventory"&&<div className="space-y-3"><form onSubmit={addInventory} className="bg-white rounded-xl border p-4 space-y-2"><h2 className="font-semibold text-sm">Add blood batch</h2><div className="grid grid-cols-2 gap-2"><select value={inventory.bloodGroup} onChange={e=>setInventory({...inventory,bloodGroup:e.target.value})} className="h-10 border rounded-lg px-2 text-sm">{groups.map(x=><option key={x}>{x}</option>)}</select><select value={inventory.component} onChange={e=>setInventory({...inventory,component:e.target.value})} className="h-10 border rounded-lg px-2 text-sm">{components.map(x=><option key={x}>{x}</option>)}</select></div><input required type="number" min="0" value={inventory.unitsAvailable} onChange={e=>setInventory({...inventory,unitsAvailable:e.target.value})} placeholder="Units" className="w-full h-10 border rounded-lg px-3 text-sm"/><input value={inventory.batchNumber} onChange={e=>setInventory({...inventory,batchNumber:e.target.value})} placeholder="Batch number" className="w-full h-10 border rounded-lg px-3 text-sm"/><div className="grid grid-cols-2 gap-2"><input type="date" value={inventory.expiryDate} onChange={e=>setInventory({...inventory,expiryDate:e.target.value})} className="h-10 border rounded-lg px-3 text-sm"/><input value={inventory.storageLocation} onChange={e=>setInventory({...inventory,storageLocation:e.target.value})} placeholder="Storage location" className="h-10 border rounded-lg px-3 text-sm"/></div><button className="h-10 px-4 rounded-lg bg-[#c2183a] text-white text-sm">Add batch</button></form><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Inventory</h2>{data.inventory.map(x=><div key={x.id} className="py-2 border-b last:border-0 flex justify-between gap-2"><div><div className="font-medium text-sm">{x.bloodGroup} · {x.component}</div><div className="text-xs text-gray-500">Batch {x.batchNumber||"—"} · {x.storageLocation||"No location"}</div></div><div className="text-right"><div className="text-sm font-semibold">{x.unitsAvailable} available</div><div className="text-xs text-gray-500">{x.unitsReserved} reserved</div></div></div>)}{data.inventory.length===0&&<p className="text-xs text-gray-400">No blood inventory yet.</p>}</div></div>}

    {tab==="requests"&&<div className="space-y-3"><form onSubmit={addRequest} className="bg-white rounded-xl border p-4 space-y-2"><h2 className="font-semibold text-sm">New blood request</h2><select required value={request.patientId} onChange={e=>setRequest({...request,patientId:e.target.value})} className="w-full h-10 border rounded-lg px-2 text-sm"><option value="">Select patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name} · {p.phone}</option>)}</select><div className="grid grid-cols-2 gap-2"><select value={request.bloodGroup} onChange={e=>setRequest({...request,bloodGroup:e.target.value})} className="h-10 border rounded-lg px-2 text-sm">{groups.map(x=><option key={x}>{x}</option>)}</select><select value={request.component} onChange={e=>setRequest({...request,component:e.target.value})} className="h-10 border rounded-lg px-2 text-sm">{components.map(x=><option key={x}>{x}</option>)}</select></div><div className="grid grid-cols-2 gap-2"><input required type="number" min="1" value={request.unitsRequested} onChange={e=>setRequest({...request,unitsRequested:e.target.value})} placeholder="Units" className="h-10 border rounded-lg px-3 text-sm"/><select value={request.urgency} onChange={e=>setRequest({...request,urgency:e.target.value})} className="h-10 border rounded-lg px-2 text-sm"><option>Routine</option><option>Urgent</option><option>Emergency</option></select></div><select value={request.crossMatchStatus} onChange={e=>setRequest({...request,crossMatchStatus:e.target.value})} className="w-full h-10 border rounded-lg px-2 text-sm"><option>Not Started</option><option>Pending</option><option>Compatible</option><option>Incompatible</option></select><button className="h-10 px-4 rounded-lg bg-[#c2183a] text-white text-sm">Create request</button></form><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Requests</h2>{data.requests.map(x=><div key={x.id} className="py-3 border-b last:border-0"><div className="flex justify-between gap-2"><div><div className="font-medium text-sm">{x.patient?.name||"Patient"} · {x.bloodGroup} {x.component}</div><div className="text-xs text-gray-500">{x.unitsRequested} unit(s) · {x.urgency} · cross-match: {x.crossMatchStatus}</div></div><span className="text-xs rounded-full bg-gray-100 px-2 py-1 h-fit">{x.status}</span></div>{x.status==="Requested"&&<button onClick={()=>reserve(x.id)} className="mt-2 mr-2 text-xs rounded-lg border px-3 py-2">Reserve</button>}{(x.status==="Requested"||x.status==="Reserved")&&<button onClick={()=>fulfil(x.id)} className="mt-2 text-xs rounded-lg bg-[#c2183a] text-white px-3 py-2">Fulfill</button>}</div>)}{data.requests.length===0&&<p className="text-xs text-gray-400">No blood requests yet.</p>}</div></div>}

    {tab==="donors"&&<div className="space-y-3"><form onSubmit={addDonor} className="bg-white rounded-xl border p-4 space-y-2"><h2 className="font-semibold text-sm">Register donor</h2><input required value={donor.name} onChange={e=>setDonor({...donor,name:e.target.value})} placeholder="Donor name" className="w-full h-10 border rounded-lg px-3 text-sm"/><div className="grid grid-cols-2 gap-2"><select value={donor.bloodGroup} onChange={e=>setDonor({...donor,bloodGroup:e.target.value})} className="h-10 border rounded-lg px-2 text-sm">{groups.map(x=><option key={x}>{x}</option>)}</select><input value={donor.phone} onChange={e=>setDonor({...donor,phone:e.target.value})} placeholder="Phone" className="h-10 border rounded-lg px-3 text-sm"/></div><input value={donor.donorCode} onChange={e=>setDonor({...donor,donorCode:e.target.value})} placeholder="Donor code" className="w-full h-10 border rounded-lg px-3 text-sm"/><input type="date" value={donor.lastDonationDate} onChange={e=>setDonor({...donor,lastDonationDate:e.target.value})} className="w-full h-10 border rounded-lg px-3 text-sm"/><button className="h-10 px-4 rounded-lg bg-[#c2183a] text-white text-sm">Register donor</button></form><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Donor registry</h2>{data.donors.map(x=><div key={x.id} className="py-2 border-b last:border-0"><div className="font-medium text-sm">{x.name} · {x.bloodGroup}</div><div className="text-xs text-gray-500">{x.phone||"No phone"} · {x.status} · Last donation: {x.lastDonationDate?new Date(x.lastDonationDate).toLocaleDateString():"—"}</div></div>)}{data.donors.length===0&&<p className="text-xs text-gray-400">No donors registered.</p>}</div></div>}
  </AppShell>;
}
