import { LAB_CATALOG, RADIOLOGY_CATALOG, type DiagnosticCatalogItem } from "@/lib/diagnostic-catalog";

const make = (items: Array<[string,string,string,string?]> , modality: string): DiagnosticCatalogItem[] => items.map(([id,name,category,flags]) => ({ id, name, category, modality, isInpatientRoutine: false, requiresFasting: false, isOutsourced: false, requiresContrastConsent: Boolean(flags?.includes("contrast")) }));

// Additional commonly ordered investigations across major clinical specialties.
const EXTRA_LABS = make([
  ["cbc-smear","CBC + Peripheral Smear Review","Hematology"],["retic-index","Reticulocyte Production Index","Hematology"],["direct-coombs","Direct Antiglobulin Test (DAT)","Hematology"],["indirect-coombs","Indirect Antiglobulin Test (IAT)","Hematology"],["bleeding-time","Bleeding Time","Hematology"],["clotting-time","Clotting Time","Hematology"],["factor-v","Factor V Assay","Hematology"],["factor-xi","Factor XI Assay","Hematology"],["factor-xii","Factor XII Assay","Hematology"],["protein-c","Protein C Activity","Hematology"],["protein-s","Protein S Activity","Hematology"],["antithrombin","Antithrombin III","Hematology"],["jak2","JAK2 V617F Mutation","Hematology / Molecular"],["bcr-abl","BCR-ABL1 PCR","Hematology / Molecular"],["flow-leukemia","Leukemia Flow Cytometry Panel","Hematology / Oncology"],
  ["bun","Blood Urea Nitrogen (BUN)","Biochemistry"],["e-gfr","Estimated GFR","Nephrology"],["urine-sodium","Urine Sodium","Nephrology"],["urine-potassium","Urine Potassium","Nephrology"],["urine-chloride","Urine Chloride","Nephrology"],["fractional-na","Fractional Excretion of Sodium","Nephrology"],["beta2-microglobulin","Beta-2 Microglobulin","Nephrology"],["p3np","P3NP","Hepatology"],["ggt","Gamma GT (GGT)","Hepatology"],["5nt","5'-Nucleotidase","Hepatology"],["pt-inr","PT / INR","Hematology"],["aptt","aPTT","Hematology"],["fibrinogen","Fibrinogen","Hematology"],
  ["il6","Interleukin-6 (IL-6)","Inflammation"],["il1","Interleukin-1 Beta","Inflammation"],["tnfa","TNF-alpha","Inflammation"],["ferritin-inflammatory","Ferritin - Inflammatory Marker","Inflammation"],["sepsis-panel","Sepsis Biomarker Panel","Critical Care"],["blood-gas-venous","Venous Blood Gas with Lactate","Critical Care"],
  ["anti-thyroid-panel","Thyroid Autoimmune Panel","Endocrinology"],["reverse-t3","Reverse T3","Endocrinology"],["thyroglobulin","Thyroglobulin","Endocrinology"],["insulin-2h","2-Hour Insulin","Endocrinology"],["metanephrine","Plasma Free Metanephrines","Endocrinology"],["normetanephrine","Plasma Normetanephrine","Endocrinology"],["aldosterone","Aldosterone","Endocrinology"],["renin","Plasma Renin Activity","Endocrinology"],["aldosterone-renin","Aldosterone/Renin Ratio","Endocrinology"],["dexamethasone","Dexamethasone Suppression Test","Endocrinology"],
  ["ck-total","Total CK","Cardiology"],["lipoprotein-a","Lipoprotein(a)","Cardiology"],["apo-a1","Apolipoprotein A1","Cardiology"],["apo-b","Apolipoprotein B","Cardiology"],["homocysteine","Homocysteine","Cardiology"],["hs-troponin","High Sensitivity Troponin","Cardiology"],["myoglobin","Serum Myoglobin","Cardiology"],
  ["pro-bnp","NT-proBNP","Cardiology"],["dengue-ns1","Dengue NS1 Antigen","Infectious Disease"],["dengue-igg","Dengue IgG","Infectious Disease"],["dengue-igm","Dengue IgM","Infectious Disease"],["malaria-pcr","Malaria PCR","Infectious Disease"],["tb-igra","Interferon Gamma Release Assay (IGRA)","Infectious Disease"],["brucella","Brucella IgM/IgG","Infectious Disease"],["rickettsial","Rickettsial Serology","Infectious Disease"],["scrub","Scrub Typhus IgM","Infectious Disease"],["hiv-vl","HIV Viral Load","Infectious Disease"],["cmv-pcr","CMV PCR","Infectious Disease"],["ebv-pcr","EBV PCR","Infectious Disease"],["ebv-serology","EBV Serology","Infectious Disease"],["herpes-pcr","HSV PCR","Infectious Disease"],
  ["stool-calprotectin","Fecal Calprotectin Quantitative","Gastroenterology"],["stool-giardia","Stool Giardia Antigen","Gastroenterology"],["stool-cdiff","C. difficile Toxin A/B + GDH","Gastroenterology"],["stool-hp","H. pylori Stool Antigen","Gastroenterology"],["fecal-alpha1","Fecal Alpha-1 Antitrypsin","Gastroenterology"],["fecal-osmotic","Stool Electrolytes / Osmotic Gap","Gastroenterology"],["pancreatic-function","Pancreatic Function Panel","Gastroenterology"],["liver-autoimmune","Autoimmune Liver Panel","Hepatology"],["liver-fibrosis","Liver Fibrosis Panel","Hepatology"],["hbsab","Anti-HBs","Hepatology"],["hbc-total","Total Anti-HBc","Hepatology"],["hbeag","HBeAg","Hepatology"],["anti-hbe","Anti-HBe","Hepatology"],["hepatitis-d","Hepatitis D Antibody","Hepatology"],["hepatitis-e-igg","Hepatitis E IgG","Hepatology"],
  ["ana-profile","ANA Profile","Rheumatology"],["myositis-panel","Myositis Antibody Panel","Rheumatology"],["scleroderma-panel","Systemic Sclerosis Panel","Rheumatology"],["vasculitis-panel","Vasculitis Panel","Rheumatology"],["complement","Complement C3/C4","Rheumatology"],["cryoglobulin","Cryoglobulins","Rheumatology"],["uric-acid-24h","24-Hour Urine Uric Acid","Rheumatology"],["hla-b51","HLA-B51","Rheumatology"],
  ["csf-meningitis","CSF Meningitis/Encephalitis PCR Panel","Neurology"],["csf-cytology","CSF Cytology","Neurology"],["csf-cryptococcus","CSF Cryptococcal Antigen","Neurology"],["csf-tb","CSF TB PCR","Neurology"],["nmo-aqp4","AQP4 Antibody","Neurology"],["miller-fisher","Ganglioside Antibody Panel","Neurology"],["paraneoplastic","Paraneoplastic Panel","Neurology"],["neurofilament","Neurofilament Light Chain","Neurology"],
  ["amh-2","AMH","Gynecology / Fertility"],["inhibin-b","Inhibin B","Gynecology / Fertility"],["day21-prog","Day-21 Progesterone","Gynecology"],["papsmear","Pap Smear Cytology","Gynecology"],["hpv-genotype","HPV Genotyping","Gynecology"],["vaginal-panel","Vaginal Infection PCR Panel","Gynecology"],["group-b-strep","Group B Streptococcus Screen","Obstetrics"],["preeclampsia","Preeclampsia Biomarker Panel","Obstetrics"],
  ["ige-total","Total IgE","Immunology"],["ige-specific","Specific IgE Allergy Panel","Immunology"],["immunoglobulins","IgG / IgA / IgM","Immunology"],["igg-subclasses","IgG Subclasses","Immunology"],["serum-free-light","Serum Free Light Chains","Oncology"],["immunofixation","Serum Immunofixation","Oncology"],["beta2","Beta-2 Microglobulin","Oncology"],["ldh-oncology","LDH Tumor Marker","Oncology"],
  ["pap-test","Pap Test","Pathology"],["fnac","FNAC Cytology","Pathology"],["body-fluid","Body Fluid Analysis","Pathology"],["pleural-fluid","Pleural Fluid Analysis","Pathology"],["ascitic-fluid","Ascitic Fluid Analysis","Pathology"],["synovial-fluid","Synovial Fluid Analysis","Pathology"],["biopsy-histo","Histopathology Biopsy","Histopathology"],["ihc-panel","Immunohistochemistry Panel","Histopathology"],["molecular-oncology","Molecular Oncology Panel","Molecular Pathology"]
], "Laboratory");

const EXTRA_IMAGING = make([
  ["xr-chest-pa","Chest X-ray PA","X-ray"],["xr-chest-ap","Chest X-ray AP","X-ray"],["xr-rib","Rib X-ray Series","X-ray"],["xr-abdomen","Abdominal X-ray","X-ray"],["xr-kub","KUB X-ray","X-ray"],["xr-spine-cervical","Cervical Spine X-ray","X-ray"],["xr-spine-dorsal","Dorsal Spine X-ray","X-ray"],["xr-spine-lumbar","Lumbar Spine X-ray","X-ray"],["xr-pelvis","Pelvis X-ray","X-ray"],["xr-hip","Hip X-ray","X-ray"],["xr-knee","Knee X-ray","X-ray"],["xr-shoulder","Shoulder X-ray","X-ray"],["xr-elbow","Elbow X-ray","X-ray"],["xr-wrist","Wrist X-ray","X-ray"],["xr-hand","Hand X-ray","X-ray"],["xr-ankle","Ankle X-ray","X-ray"],["xr-foot","Foot X-ray","X-ray"],["xr-skull","Skull X-ray","X-ray"],["xr-sinus","PNS / Sinus X-ray","X-ray"],["xr-mammography","Mammography","Mammography"],
  ["usg-whole-abdomen","Ultrasound Whole Abdomen","Ultrasound"],["usg-upper-abdomen","Ultrasound Upper Abdomen","Ultrasound"],["usg-lower-abdomen","Ultrasound Lower Abdomen","Ultrasound"],["usg-pelvis","Ultrasound Pelvis","Ultrasound"],["usg-kub","Ultrasound KUB","Ultrasound"],["usg-hepatobiliary","Ultrasound Hepatobiliary System","Ultrasound"],["usg-pancreas","Ultrasound Pancreas","Ultrasound"],["usg-thyroid","Ultrasound Thyroid","Ultrasound"],["usg-neck","Ultrasound Neck","Ultrasound"],["usg-breast","Ultrasound Breast","Ultrasound"],["usg-scrotum","Ultrasound Scrotum","Ultrasound"],["usg-doppler-carotid","Carotid Doppler","Doppler"],["usg-doppler-venous","Venous Doppler Lower Limb","Doppler"],["usg-doppler-arterial","Arterial Doppler Lower Limb","Doppler"],["usg-portal","Portal Vein Doppler","Doppler"],["usg-renal-doppler","Renal Artery Doppler","Doppler"],["usg-obstetric","Obstetric Ultrasound","Ultrasound"],["usg-nt","NT / NB Scan","Ultrasound"],["usg-level2","Level II / Anomaly Scan","Ultrasound"],["usg-growth","Obstetric Growth Scan","Ultrasound"],["usg-fetal-doppler","Fetal Colour Doppler","Doppler"],["usg-transvaginal","Transvaginal Ultrasound","Ultrasound"],["usg-transrectal","Transrectal Ultrasound","Ultrasound"],["usg-elastography","Ultrasound Elastography","Ultrasound"],["fibroscan","FibroScan / Liver Elastography","Elastography"],
  ["ct-head","CT Head / Brain","CT"],["ct-chest","CT Chest","CT"],["ct-abdomen","CT Abdomen","CT"],["ct-pelvis","CT Pelvis","CT"],["ct-abdomen-pelvis","CT Abdomen and Pelvis","CT"],["ct-kub","CT KUB","CT"],["ct-pns","CT PNS","CT"],["ct-spine-cervical","CT Cervical Spine","CT"],["ct-spine-dorsal","CT Dorsal Spine","CT"],["ct-spine-lumbar","CT Lumbar Spine","CT"],["ct-hrct-chest","HRCT Chest","CT"],["ct-angiography-brain","CT Cerebral Angiography","CT Angiography","contrast"],["ct-angio-coronary","CT Coronary Angiography","CT Angiography","contrast"],["ct-pulmonary-angio","CT Pulmonary Angiography","CT Angiography","contrast"],["ct-aortogram","CT Aortogram","CT Angiography","contrast"],["ct-triple-phase-liver","Triple Phase CT Liver","CT","contrast"],["ct-enterography","CT Enterography","CT","contrast"],["ct-colonography","CT Colonography","CT","contrast"],["ct-urography","CT Urography","CT","contrast"],["ct-perfusion","CT Perfusion Brain","CT","contrast"],["ct-trauma","CT Polytrauma","CT","contrast"],
  ["mri-brain","MRI Brain","MRI"],["mri-brain-contrast","MRI Brain with Contrast","MRI","contrast"],["mri-spine-cervical","MRI Cervical Spine","MRI"],["mri-spine-dorsal","MRI Dorsal Spine","MRI"],["mri-spine-lumbar","MRI Lumbar Spine","MRI"],["mri-whole-spine","MRI Whole Spine","MRI"],["mri-orbit","MRI Orbits","MRI"],["mri-pituitary","MRI Pituitary","MRI"],["mri-iac","MRI Internal Auditory Canals","MRI"],["mri-mra","MR Angiography","MRI"],["mri-mrv","MR Venography","MRI"],["mri-mrcp","MRCP","MRI"],["mri-liver","MRI Liver","MRI"],["mri-abdomen","MRI Abdomen","MRI"],["mri-pelvis","MRI Pelvis","MRI"],["mri-enterography","MR Enterography","MRI"],["mri-prostate","MRI Prostate","MRI"],["mri-breast","MRI Breast","MRI"],["mri-knee","MRI Knee","MRI"],["mri-shoulder","MRI Shoulder","MRI"],["mri-hip","MRI Hip","MRI"],["mri-ankle","MRI Ankle","MRI"],["mri-wrist","MRI Wrist","MRI"],["mri-foot","MRI Foot","MRI"],["mri-cardiac","Cardiac MRI","MRI"],["mri-perfusion","MRI Brain Perfusion","MRI"],["mri-spectroscopy","MR Spectroscopy","MRI"],["mri-dti","Diffusion Tensor Imaging (DTI)","MRI"],
  ["pet-ct","PET-CT","Nuclear Medicine"],["pet-mri","PET-MRI","Nuclear Medicine"],["bone-scan","Whole Body Bone Scan","Nuclear Medicine"],["thyroid-scan","Thyroid Scan","Nuclear Medicine"],["renal-scan","DTPA Renal Scan","Nuclear Medicine"],["dmsa","DMSA Renal Scan","Nuclear Medicine"],["hida","HIDA Scan","Nuclear Medicine"],["spect-ct","SPECT-CT","Nuclear Medicine"],
  ["echo-2d","2D Echocardiography","Cardiac Imaging"],["echo-3d","3D Echocardiography","Cardiac Imaging"],["echo-stress","Stress Echocardiography","Cardiac Imaging"],["echo-fetal","Fetal Echocardiography","Cardiac Imaging"],["ecg","ECG","Cardiac Diagnostics"],["holter","Holter Monitoring","Cardiac Diagnostics"],["tmt","Treadmill Test (TMT)","Cardiac Diagnostics"],["coronary-angio","Coronary Angiography / Cath Lab","Interventional Cardiology"],["dsa","Digital Subtraction Angiography (DSA)","Interventional Radiology"],["fluoroscopy","Fluoroscopy Study","Fluoroscopy"],["barium-swallow","Barium Swallow","Fluoroscopy"],["barium-meal","Barium Meal Follow Through","Fluoroscopy"],["barium-enema","Barium Enema","Fluoroscopy"],["hsg","Hysterosalpingography (HSG)","Fluoroscopy"],["vcug","MCU / VCUG","Fluoroscopy"],
  ["eeG","EEG","Neurodiagnostics"],["emg","EMG / NCS","Neurodiagnostics"],["eeg-sleep","Sleep EEG","Neurodiagnostics"],["sleep-study","Polysomnography / Sleep Study","Sleep Diagnostics"],["spirometry","Spirometry","Pulmonary Diagnostics"],["pft","Pulmonary Function Test","Pulmonary Diagnostics"],["dlco","DLCO","Pulmonary Diagnostics"],["bronchoscopy","Bronchoscopy","Endoscopy"],["endoscopy","Upper GI Endoscopy","Endoscopy"],["colonoscopy","Colonoscopy","Endoscopy"],["eus","Endoscopic Ultrasound (EUS)","Endoscopy"],["ercp","ERCP","Endoscopy"],["fibrobronchoscopy","Flexible Bronchoscopy","Endoscopy"]
], "Imaging");

const dedupe = (items: DiagnosticCatalogItem[]) => Array.from(new Map(items.map((x) => [x.id, x])).values()).sort((a,b) => a.name.localeCompare(b.name));

export const FULL_LAB_CATALOG = dedupe([...LAB_CATALOG, ...EXTRA_LABS]);
export const FULL_RADIOLOGY_CATALOG = dedupe([...RADIOLOGY_CATALOG, ...EXTRA_IMAGING]);
