export type DiagnosticCatalogItem = {
  id: string;
  name: string;
  category: string;
  modality: string;
  components?: string[];
  isInpatientRoutine: boolean;
  requiresFasting: boolean;
  isOutsourced: boolean;
  requiresContrastConsent: boolean;
};

type Flags = Partial<Pick<DiagnosticCatalogItem, "isInpatientRoutine" | "requiresFasting" | "isOutsourced" | "requiresContrastConsent">>;
type Entry = [id: string, name: string, category: string, components?: string[], flags?: Flags];

const lab = ([id, name, category, components = [], flags = {}]: Entry): DiagnosticCatalogItem => ({ id, name, category, modality: "Laboratory", components, isInpatientRoutine: false, requiresFasting: false, isOutsourced: false, requiresContrastConsent: false, ...flags });
const img = ([id, name, category, , flags = {}]: Entry, modality: string): DiagnosticCatalogItem => ({ id, name, category, modality, isInpatientRoutine: false, requiresFasting: false, isOutsourced: false, requiresContrastConsent: false, ...flags });

const LABS: Entry[] = [
  ["cbc","Complete Blood Count (CBC) with Differential","Hematology",["Hb","TLC","DLC","Platelets","RBC indices"],{isInpatientRoutine:true}],
  ["retic","Reticulocyte Count","Hematology"],["pbs","Peripheral Blood Smear","Hematology"],["esr","ESR","Hematology"],["coag","Coagulation Profile","Hematology",["PT","INR","aPTT","Fibrinogen"]],["d-dimer","D-Dimer","Hematology"],["factor-viii","Factor VIII Assay","Hematology"],["factor-ix","Factor IX Assay","Hematology"],["vwd","Von Willebrand Factor Panel","Hematology"],["hb-electro","Hemoglobin Electrophoresis / HPLC","Hematology"],["g6pd","G6PD Assay","Hematology"],["sickle","Sickle Cell Screen","Hematology"],
  ["lft","Liver Function Test (LFT)","Biochemistry",["Bilirubin","AST","ALT","ALP","Protein","Albumin","Globulin"],{isInpatientRoutine:true}],["rft","Renal Function Test (RFT / KFT)","Biochemistry",["Creatinine","Urea/BUN","Uric Acid","Electrolytes"],{isInpatientRoutine:true}],["electrolytes","Serum Electrolytes","Biochemistry",["Na","K","Cl","HCO3"]],["calcium","Serum Calcium","Biochemistry"],["ionized-calcium","Ionized Calcium","Biochemistry"],["magnesium","Serum Magnesium","Biochemistry"],["phosphate","Serum Phosphate","Biochemistry"],["osmolality","Serum Osmolality","Biochemistry"],["ammonia","Plasma Ammonia","Biochemistry"],["lactate","Serum Lactate","Biochemistry"],["amylase","Serum Amylase","Biochemistry"],["lipase","Serum Lipase","Biochemistry"],
  ["lipid","Lipid Profile","Biochemistry",["Total Cholesterol","Triglycerides","HDL","LDL","VLDL"],{requiresFasting:true}],["uric-acid","Uric Acid","Biochemistry"],["ldh","LDH","Biochemistry"],["ck","Creatine Kinase (CK/CPK)","Biochemistry"],
  ["fbs","Fasting Blood Sugar","Endocrinology"],["ppbs","Postprandial Blood Sugar","Endocrinology"],["rbs","Random Blood Sugar","Endocrinology"],["hba1c","HbA1c","Endocrinology"],["ogtt","Oral Glucose Tolerance Test","Endocrinology"],["fructosamine","Fructosamine","Endocrinology"],["fasting-insulin","Fasting Insulin","Endocrinology"],["c-peptide","C-Peptide","Endocrinology"],["tsh","TSH","Endocrinology"],["ft3","Free T3","Endocrinology"],["ft4","Free T4","Endocrinology"],["t3","Total T3","Endocrinology"],["t4","Total T4","Endocrinology"],["anti-tpo","Anti-TPO Antibody","Endocrinology"],["anti-tg","Anti-Thyroglobulin Antibody","Endocrinology"],["trab","TSH Receptor Antibody (TRAb)","Endocrinology"],["cortisol","Serum Cortisol","Endocrinology"],["acth","ACTH","Endocrinology"],["prolactin","Prolactin","Endocrinology"],["lh","LH","Endocrinology"],["fsh","FSH","Endocrinology"],["estradiol","Estradiol (E2)","Endocrinology"],["progesterone","Progesterone","Endocrinology"],["testosterone","Total Testosterone","Endocrinology"],["shbg","SHBG","Endocrinology"],["igf1","IGF-1","Endocrinology"],["pth","Parathyroid Hormone (PTH)","Endocrinology"],["vitd","25-OH Vitamin D","Endocrinology"],["b12","Vitamin B12","Nutrition"],["folate","Folate","Nutrition"],["iron","Iron Studies","Nutrition",["Iron","TIBC","Transferrin Saturation","Ferritin"]],["ferritin","Ferritin","Nutrition"],
  ["abg","Arterial Blood Gas (ABG)","Critical Care",["pH","pCO2","pO2","HCO3","Lactate"],{isInpatientRoutine:true}],["vbg","Venous Blood Gas (VBG)","Critical Care"],["procalcitonin","Procalcitonin","Infectious Disease",[],{isInpatientRoutine:true}],["crp","CRP","Infectious Disease"],["hscrp","High-Sensitivity CRP","Cardiology"],["troponin","High-Sensitivity Troponin I/T","Cardiology",[],{isInpatientRoutine:true}],["ckmb","CK-MB","Cardiology"],["bnp","BNP / NT-proBNP","Cardiology"],
  ["urine-rm","Urine Routine & Microscopy","Urinalysis",["pH","Specific Gravity","Protein","Glucose","Ketones","Nitrite","Leukocyte Esterase","RBC","Pus Cells","Casts","Crystals"]],["urine-culture","Urine Culture & Sensitivity","Microbiology"],["urine-acr","Urine Albumin/Creatinine Ratio","Nephrology"],["urine-pcr","Urine Protein/Creatinine Ratio","Nephrology"],["24h-protein","24-Hour Urine Protein","Nephrology"],["creatinine-clearance","Creatinine Clearance","Nephrology"],["cystatin-c","Cystatin C","Nephrology"],["urine-osmolality","Urine Osmolality","Nephrology"],["urine-electrolytes","Urine Electrolytes","Nephrology"],
  ["stool-rm","Stool Routine & Microscopy","Gastroenterology / Stool",["Color","Consistency","Mucus","Pus Cells","RBC","Ova","Cysts","Parasites"]],["stool-occult","Stool Occult Blood (FOBT/FIT)","Gastroenterology / Stool"],["fecal-calprotectin","Fecal Calprotectin","Gastroenterology / Stool"],["fecal-lactoferrin","Fecal Lactoferrin","Gastroenterology / Stool"],["fecal-elastase","Fecal Pancreatic Elastase","Gastroenterology / Stool"],["stool-fat","Stool Fat / Fecal Fat","Gastroenterology / Stool"],["stool-culture","Stool Culture & Sensitivity","Gastroenterology / Microbiology"],["stool-reducing","Stool Reducing Substances","Pediatrics / Gastroenterology"],["cdiff-gdh","C. difficile GDH Antigen","Gastroenterology / Stool"],["cdiff-toxin-ab","C. difficile Toxin A & B","Gastroenterology / Stool"],["cdiff-gdh-toxin","C. difficile GDH + Toxin A/B","Gastroenterology / Stool",["GDH","Toxin A","Toxin B"]],["cdiff-pcr","C. difficile PCR / NAAT","Gastroenterology / Microbiology"],["hp-stool","H. pylori Stool Antigen","Gastroenterology / Stool"],["hp-urea","H. pylori Urea Breath Test","Gastroenterology"],["gi-pcr","GI Pathogen PCR Panel","Gastroenterology / Microbiology"],["gi-parasite","GI Parasite PCR Panel","Gastroenterology / Microbiology"],["giardia","Giardia Antigen","Gastroenterology / Microbiology"],["cryptosporidium","Cryptosporidium Antigen","Gastroenterology / Microbiology"],["entamoeba","Entamoeba histolytica Antigen","Gastroenterology / Microbiology"],["celiac","Celiac Disease Panel","Gastroenterology / Immunology",["tTG-IgA","Total IgA","EMA"]],["ttg-iga","Tissue Transglutaminase IgA","Gastroenterology / Immunology"],["ttg-igg","Tissue Transglutaminase IgG","Gastroenterology / Immunology"],["endomysial","Endomysial Antibody IgA","Gastroenterology / Immunology"],["gastrin","Serum Gastrin","Gastroenterology"],["chromogranin-a","Chromogranin A","Gastroenterology / Oncology"],["ca19-9","CA 19-9","Gastroenterology / Oncology"],["cea","CEA","Gastroenterology / Oncology"],
  ["viral-hepatitis","Viral Hepatitis Panel","Hepatology",["HBsAg","Anti-HBc","Anti-HBs","HBeAg","Anti-HBe","Anti-HCV"]],["hbv-dna","HBV DNA PCR / Viral Load","Hepatology"],["hcv-rna","HCV RNA PCR / Viral Load","Hepatology"],["hcv-genotype","HCV Genotype","Hepatology"],["hepatitis-a","Hepatitis A IgM","Hepatology"],["hepatitis-e","Hepatitis E IgM","Hepatology"],["afp","AFP","Hepatology / Oncology"],["ceruloplasmin","Ceruloplasmin","Hepatology / Neurology"],["serum-copper","Serum Copper","Hepatology"],["urine-copper","24-Hour Urine Copper","Hepatology"],["ama","Anti-Mitochondrial Antibody (AMA)","Hepatology / Autoimmune"],["asma","Anti-Smooth Muscle Antibody (ASMA)","Hepatology / Autoimmune"],["anti-lkm","Anti-LKM-1","Hepatology / Autoimmune"],["ig-g4","IgG4","Hepatology / Immunology"],["bile-acids","Serum Bile Acids","Hepatology"],["fibrotest","FibroTest / FibroSure","Hepatology"],["peth","Phosphatidylethanol (PEth)","Hepatology / Toxicology"],
  ["blood-culture","Blood Culture & Sensitivity","Microbiology",["Aerobic","Anaerobic"],{isInpatientRoutine:true}],["sputum-culture","Sputum Culture & Sensitivity","Microbiology"],["wound-culture","Wound/Pus Culture & Sensitivity","Microbiology"],["gram","Gram Stain","Microbiology"],["afb","AFB Smear","Microbiology"],["afb-culture","Mycobacterial Culture","Microbiology"],["fungal-koh","KOH/Fungal Mount","Microbiology"],["genexpert-tb","GeneXpert / CBNAAT TB","Microbiology"],["hiv","HIV 1/2 Ag/Ab","Serology"],["hbsag","HBsAg","Serology"],["anti-hcv","Anti-HCV","Serology"],["vdrl","VDRL/RPR","Serology"],["dengue","Dengue NS1/IgM/IgG","Infectious Disease"],["malaria","Malaria Antigen/Smear","Infectious Disease"],["typhoid","Typhoid Serology","Infectious Disease"],["chikungunya","Chikungunya IgM/IgG","Infectious Disease"],["leptospira","Leptospira IgM","Infectious Disease"],["covid","SARS-CoV-2 RT-PCR/Antigen","Infectious Disease"],["influenza","Influenza A/B PCR","Infectious Disease"],["rsv","RSV PCR/Antigen","Pediatrics / Infectious Disease"],["resp-panel","Respiratory Viral PCR Panel","Infectious Disease"],
  ["rf","Rheumatoid Factor (RF)","Rheumatology"],["anti-ccp","Anti-CCP","Rheumatology"],["ana","ANA by IFA","Rheumatology / Autoimmune"],["ena","ENA / ANA Profile","Rheumatology / Autoimmune",["dsDNA","Sm","RNP","SSA/Ro","SSB/La","Scl-70","Jo-1","Centromere"]],["dsdna","Anti-dsDNA","Rheumatology"],["anca","ANCA Profile","Rheumatology",["PR3/c-ANCA","MPO/p-ANCA"]],["c3c4","Complement C3/C4","Rheumatology"],["ch50","CH50","Rheumatology / Immunology"],["hla-b27","HLA-B27","Rheumatology"],["aps","Antiphospholipid Syndrome Panel","Rheumatology",["Lupus Anticoagulant","Anticardiolipin","Beta-2 Glycoprotein I"]],["aldolase","Aldolase","Rheumatology / Neurology"],
  ["csf-routine","CSF Routine & Biochemistry","Neurology / CSF",["Cells","Protein","Glucose","Gram Stain"]],["csf-culture","CSF Culture","Neurology / CSF"],["csf-oligoclonal","CSF Oligoclonal Bands","Neurology / CSF"],["csf-igg-index","CSF IgG Index","Neurology / CSF"],["autoimmune-encephalitis","Autoimmune Encephalitis Antibody Panel","Neurology"],["paraneoplastic-neuro","Paraneoplastic Neurologic Antibody Panel","Neurology"],["aquaporin4","AQP4/NMO-IgG","Neurology"],["mog","MOG-IgG","Neurology"],["nmda","NMDA Receptor Antibody","Neurology"],["lgi1","LGI1 Antibody","Neurology"],["caspr2","CASPR2 Antibody","Neurology"],["achr","AChR Antibody","Neurology"],["musk","MuSK Antibody","Neurology"],["b1","Vitamin B1","Neurology / Nutrition"],["copper","Serum Copper","Neurology"],
  ["psa","PSA Total","Urology"],["free-psa","Free PSA","Urology"],["semen","Semen Analysis","Andrology"],["urine-cytology","Urine Cytology","Urology"],["beta-hcg","Beta-hCG","Gynecology / Obstetrics"],["amh","Anti-Müllerian Hormone (AMH)","Gynecology / Fertility"],["prenatal","Prenatal Screening Panel","Obstetrics"],["torch","TORCH Panel","Obstetrics / Pediatrics"],["rubella","Rubella IgG/IgM","Obstetrics"],["toxoplasma","Toxoplasma IgG/IgM","Obstetrics"],["syphilis","Syphilis Serology","Obstetrics / Infectious Disease"],["hpv","High-Risk HPV DNA","Gynecology / Molecular"],["chlamydia-gono","Chlamydia/Gonorrhea NAAT","Gynecology / Microbiology"],
  ["flow","Flow Cytometry","Hematology / Oncology"],["spep","Serum Protein Electrophoresis","Hematology / Oncology"],["immunofix","Serum Immunofixation","Hematology / Oncology"],["bcr-abl","BCR-ABL1 PCR","Hematology / Oncology"],["jak2","JAK2 V617F Mutation","Hematology / Oncology"],["calr","CALR Mutation","Hematology / Oncology"],["mpl","MPL Mutation","Hematology / Oncology"],["ldh-onco","LDH","Oncology"],["ca125","CA-125","Oncology"],["ca153","CA 15-3","Oncology"],["cea-onco","CEA","Oncology"],["psa-onco","PSA","Oncology"],["ige","Total IgE","Allergy / Immunology"],["specific-ige","Specific IgE Allergy Panel","Allergy / Immunology"],["immunoglobulins","IgG/IgA/IgM","Immunology"],["hla-typing","HLA Typing","Transplant / Immunology"],["tacrolimus","Tacrolimus Level","Therapeutic Drug Monitoring"],["cyclosporine","Cyclosporine Level","Therapeutic Drug Monitoring"],["vancomycin","Vancomycin Level","Therapeutic Drug Monitoring"],["digoxin","Digoxin Level","Therapeutic Drug Monitoring"],["lithium","Lithium Level","Toxicology / TDM"],["toxicology","Drug/Poison Toxicology Screen","Toxicology"],["blood-group","ABO & Rh Blood Grouping","Immunohematology"],["crossmatch","Crossmatch / Compatibility Testing","Immunohematology"],["dat","Direct Coombs Test (DAT)","Immunohematology"],["iat","Indirect Coombs Test (IAT)","Immunohematology"],["karyotype","Karyotyping","Cytogenetics"],["ngs","Molecular / NGS Panel","Molecular / Genetics"],["pap","Pap Smear Cytology","Cytology"],["histopath","Histopathology / Biopsy","Histopathology"],["ihc","Immunohistochemistry (IHC)","Histopathology"]
];

export const LAB_CATALOG: DiagnosticCatalogItem[] = LABS.map(lab);

const XRAY: Entry[] = [
  ["cxr-pa","Chest X-Ray PA","Radiography"],["cxr-ap","Chest X-Ray AP / Portable","Radiography"],["cxr-lateral","Chest X-Ray Lateral","Radiography"],["abdomen-xray","Abdomen X-Ray Erect / Supine","Radiography"],["kub-xray","KUB X-Ray","Radiography"],["c-spine-xray","Cervical Spine X-Ray","Radiography"],["t-spine-xray","Thoracic Spine X-Ray","Radiography"],["l-spine-xray","Lumbar Spine X-Ray","Radiography"],["pelvis-xray","Pelvis X-Ray","Radiography"],["skull-xray","Skull X-Ray","Radiography"],["pns-xray","PNS / Sinus X-Ray","Radiography"],["shoulder-xray","Shoulder X-Ray","Radiography"],["knee-xray","Knee X-Ray","Radiography"],["hip-xray","Hip X-Ray","Radiography"],["hand-xray","Hand / Wrist X-Ray","Radiography"],["foot-xray","Foot / Ankle X-Ray","Radiography"],["long-bone-xray","Long Bone X-Ray","Radiography"],["whole-spine-xray","Whole Spine / Scoliosis X-Ray","Radiography"],["dental-opg","Dental OPG","Dental Imaging"]
];
const USG: Entry[] = [
  ["usg-whole-abdomen","USG Whole Abdomen","Ultrasound"],["usg-abdomen-pelvis","USG Abdomen & Pelvis","Ultrasound"],["usg-kub","USG KUB","Ultrasound"],["usg-kub-prostate","USG KUB & Prostate","Ultrasound"],["usg-pelvis","USG Pelvis","Ultrasound"],["usg-liver","USG Liver / Hepatobiliary System","Ultrasound"],["usg-pancreas","USG Pancreas","Ultrasound"],["usg-spleen","USG Spleen","Ultrasound"],["usg-thyroid","USG Thyroid","Ultrasound"],["usg-neck","USG Neck / Salivary Glands","Ultrasound"],["usg-breast","USG Breast","Ultrasound"],["usg-scrotum","USG Scrotum / Testes","Ultrasound"],["usg-small-parts","USG Small Parts / Soft Tissue","Ultrasound"],["usg-msk","Musculoskeletal Ultrasound","Ultrasound"],["usg-obstetric","Obstetric Ultrasound","Obstetric Imaging"],["nt-scan","NT Scan","Obstetric Imaging"],["anomaly-scan","Level-II / Anomaly Scan","Obstetric Imaging"],["growth-scan","Obstetric Growth Scan","Obstetric Imaging"],["fetal-doppler","Fetal Doppler","Obstetric Imaging"],["transvaginal","Transvaginal Ultrasound","Gynecologic Imaging"],["follicular","Follicular Monitoring","Gynecologic Imaging"],["carotid-doppler","Carotid Doppler","Vascular Imaging"],["venous-doppler","Venous Doppler / DVT Study","Vascular Imaging"],["arterial-doppler","Arterial Doppler","Vascular Imaging"],["renal-doppler","Renal Artery Doppler","Vascular Imaging"],["portal-doppler","Portal Vein Doppler","Vascular Imaging"],["hepatic-doppler","Hepatic Doppler","Vascular Imaging"],["testicular-doppler","Testicular Doppler","Vascular Imaging"],["penile-doppler","Penile Doppler","Vascular Imaging"],["fast","FAST / E-FAST","Point-of-Care Ultrasound"],["pocus","POCUS / Bedside Ultrasound","Point-of-Care Ultrasound"]
];
const CT: Entry[] = [
  ["ct-brain","CT Brain / Head Plain","CT"],["cect-brain","CECT Brain","CT",[],{requiresContrastConsent:true}],["ct-stroke","CT Stroke Protocol","CT"],["ct-pns","CT PNS","CT"],["ct-orbit","CT Orbit","CT"],["ct-temporal","HRCT Temporal Bone","CT"],["ct-neck","CT Neck","CT"],["ct-chest","CT Chest","CT"],["hrct-chest","HRCT Thorax","CT"],["ct-abdomen","CT Abdomen & Pelvis","CT"],["ct-kub","CT KUB","CT"],["triphasic-liver","Triphasic CT Liver","CT",[],{requiresContrastConsent:true}],["pancreas-ct","Pancreatic Protocol CT","CT",[],{requiresContrastConsent:true}],["ct-c-spine","CT Cervical Spine","CT"],["ct-l-spine","CT Lumbar Spine","CT"],["ct-pelvis","CT Pelvis","CT"],["ct-enterography","CT Enterography","CT"],["ct-colonography","CT Colonography","CT"],["cta-coronary","CT Coronary Angiography","CT Angiography",[],{requiresContrastConsent:true}],["cta-pulmonary","CT Pulmonary Angiography","CT Angiography",[],{requiresContrastConsent:true}],["cta-carotid","CT Carotid Angiography","CT Angiography",[],{requiresContrastConsent:true}],["cta-aorta","CT Aortogram","CT Angiography",[],{requiresContrastConsent:true}],["cta-peripheral","CT Peripheral Angiography","CT Angiography",[],{requiresContrastConsent:true}],["ct-guided-biopsy","CT-Guided Biopsy / Drainage","Interventional Radiology",[],{requiresContrastConsent:true}]
];
const MRI: Entry[] = [
  ["mri-brain","MRI Brain Plain","MRI"],["mri-brain-contrast","MRI Brain with Contrast","MRI",[],{requiresContrastConsent:true}],["mri-stroke","MRI Brain Stroke Protocol","MRI"],["mri-epilepsy","MRI Brain Epilepsy Protocol","MRI"],["mri-pituitary","MRI Pituitary","MRI",[],{requiresContrastConsent:true}],["mri-orbit","MRI Orbit","MRI"],["mri-iac","MRI Internal Auditory Canal","MRI"],["mri-c-spine","MRI Cervical Spine","MRI"],["mri-t-spine","MRI Thoracic Spine","MRI"],["mri-l-spine","MRI Lumbar Spine","MRI"],["mri-whole-spine","MRI Whole Spine","MRI"],["mri-knee","MRI Knee","MSK MRI"],["mri-shoulder","MRI Shoulder","MSK MRI"],["mri-hip","MRI Hip","MSK MRI"],["mri-ankle","MRI Ankle / Foot","MSK MRI"],["mri-wrist","MRI Wrist / Hand","MSK MRI"],["mri-pelvis","MRI Pelvis","MRI"],["mri-prostate","Multiparametric MRI Prostate","MRI"],["mri-liver","MRI Liver","MRI"],["mrcp","MRCP","MRI"],["mri-enterography","MR Enterography","MRI"],["mri-breast","MRI Breast","Breast Imaging"],["mri-cardiac","Cardiac MRI","Cardiac Imaging"],["mra-brain","MRA Brain","MRA / MRV"],["mrv-brain","MRV Brain","MRA / MRV"],["mra-neck","MRA Neck / Carotids","MRA / MRV"],["mra-renal","MRA Renal Arteries","MRA / MRV"],["mra-peripheral","MRA Peripheral Vessels","MRA / MRV"]
];
const ADVANCED: Entry[] = [
  ["pet-ct","PET-CT Whole Body","Nuclear Medicine"],["fdg-pet","FDG PET-CT","Nuclear Medicine"],["psma-pet","PSMA PET-CT","Nuclear Medicine"],["dotatate-pet","DOTATATE PET-CT","Nuclear Medicine"],["bone-scan","Whole Body Bone Scan","Nuclear Medicine"],["spect-ct","SPECT-CT","Nuclear Medicine"],["thyroid-scan","Thyroid Nuclear Scan","Nuclear Medicine"],["hida","HIDA / Hepatobiliary Scan","Nuclear Medicine"],["renal-dmsa","DMSA Renal Scan","Nuclear Medicine"],["gastric-emptying","Gastric Emptying Study","Nuclear Medicine"],["dexa","DEXA / Bone Mineral Density","Bone Density"],["barium-swallow","Barium Swallow","Fluoroscopy"],["barium-meal","Barium Meal / Follow Through","Fluoroscopy"],["barium-enema","Barium Enema","Fluoroscopy"],["hsg","Hysterosalpingography (HSG)","Fluoroscopy"],["mcu","Micturating Cystourethrogram (MCU)","Fluoroscopy"],["rgu","Retrograde Urethrogram","Fluoroscopy"],["mammo-screen","Screening Mammography","Breast Imaging"],["mammo-diagnostic","Diagnostic Mammography","Breast Imaging"],["tomosynthesis","3D Breast Tomosynthesis","Breast Imaging"],["echo","2D / 3D Echocardiography","Cardiac Imaging"],["stress-echo","Stress Echocardiography","Cardiac Imaging"],["tee","Transesophageal Echocardiography (TEE)","Cardiac Imaging"],["ecg","ECG / EKG","Cardiac Diagnostics"],["tmt","Treadmill Test (TMT)","Cardiac Diagnostics"],["holter","24/48/72-Hour Holter","Cardiac Diagnostics"],["event-monitor","Event / Loop Recorder","Cardiac Diagnostics"],["upper-gi-endoscopy","Upper GI Endoscopy (EGD)","Endoscopy"],["colonoscopy","Colonoscopy","Endoscopy"],["sigmoidoscopy","Flexible Sigmoidoscopy","Endoscopy"],["ercp","ERCP","Endoscopy / Fluoroscopy"],["bronchoscopy","Bronchoscopy","Endoscopy"],["cystoscopy","Cystoscopy","Endoscopy"],["laryngoscopy","Laryngoscopy","Endoscopy"]
];

export const RADIOLOGY_CATALOG: DiagnosticCatalogItem[] = [
  ...XRAY.map((e) => img(e, "X-ray")),
  ...USG.map((e) => img(e, "Ultrasound")),
  ...CT.map((e) => img(e, "CT")),
  ...MRI.map((e) => img(e, "MRI")),
  ...ADVANCED.map((e) => img(e, e[2].includes("Nuclear") ? "Nuclear Medicine" : e[2].includes("Fluoroscopy") ? "Fluoroscopy" : e[2].includes("Cardiac") ? "Cardiac Diagnostics" : e[2].includes("Endoscopy") ? "Endoscopy" : e[2].includes("Breast") ? "Mammography" : "Diagnostic Procedure")),
];

export const DIAGNOSTIC_CATALOG: DiagnosticCatalogItem[] = [...LAB_CATALOG, ...RADIOLOGY_CATALOG];
export const DIAGNOSTIC_CATEGORIES = [...new Set(DIAGNOSTIC_CATALOG.map((x) => x.category))].sort();
export const DIAGNOSTIC_MODALITIES = [...new Set(DIAGNOSTIC_CATALOG.map((x) => x.modality))].sort();
