import { LAB_CATALOG as BASE_LABS, RADIOLOGY_CATALOG as BASE_RADIOLOGY, type DiagnosticCatalogItem } from "./diagnostic-catalog";

const lab = (id: string, name: string, category: string): DiagnosticCatalogItem => ({ id, name, category, modality: "Laboratory", isInpatientRoutine: false, requiresFasting: false, isOutsourced: false, requiresContrastConsent: false });
const imaging = (id: string, name: string, modality: string, category = modality, contrast = false): DiagnosticCatalogItem => ({ id, name, category, modality, isInpatientRoutine: false, requiresFasting: false, isOutsourced: false, requiresContrastConsent: contrast });

const EXTRA_LABS: DiagnosticCatalogItem[] = [
  ["direct-coombs","Direct Antiglobulin Test (DAT)","Hematology"],["indirect-coombs","Indirect Antiglobulin Test (IAT)","Hematology"],["protein-c","Protein C Activity","Hematology"],["protein-s","Protein S Activity","Hematology"],["antithrombin","Antithrombin III","Hematology"],["factor-v","Factor V Assay","Hematology"],["factor-xi","Factor XI Assay","Hematology"],["jak2-v617f","JAK2 V617F Mutation","Hematology / Molecular"],["bcr-abl1","BCR-ABL1 PCR","Hematology / Molecular"],
  ["bun","Blood Urea Nitrogen (BUN)","Biochemistry"],["egfr","eGFR","Nephrology"],["urine-sodium","Urine Sodium","Nephrology"],["urine-potassium","Urine Potassium","Nephrology"],["urine-chloride","Urine Chloride","Nephrology"],["cystatin-c","Cystatin C","Nephrology"],["ggt","Gamma GT (GGT)","Hepatology"],["5nt","5'-Nucleotidase","Hepatology"],
  ["aptt","aPTT","Coagulation"],["fibrinogen","Fibrinogen","Coagulation"],["d-dimer-quant","Quantitative D-Dimer","Coagulation"],["factor-viii","Factor VIII","Coagulation"],["lupus-anticoagulant","Lupus Anticoagulant","Rheumatology / Coagulation"],
  ["il6","Interleukin-6 (IL-6)","Inflammation"],["il1b","Interleukin-1 Beta","Inflammation"],["tnfa","TNF-alpha","Inflammation"],["sepsis-biomarkers","Sepsis Biomarker Panel","Critical Care"],
  ["reverse-t3","Reverse T3","Endocrinology"],["thyroglobulin","Thyroglobulin","Endocrinology"],["metanephrines","Plasma Free Metanephrines","Endocrinology"],["renin","Plasma Renin Activity","Endocrinology"],["aldosterone","Aldosterone","Endocrinology"],["aldosterone-renin","Aldosterone/Renin Ratio","Endocrinology"],["igf1","IGF-1","Endocrinology"],
  ["lipoprotein-a","Lipoprotein(a)","Cardiology"],["apo-a1","Apolipoprotein A1","Cardiology"],["apo-b","Apolipoprotein B","Cardiology"],["homocysteine","Homocysteine","Cardiology"],["myoglobin","Myoglobin","Cardiology"],
  ["tb-igra","Interferon Gamma Release Assay (IGRA)","Infectious Disease"],["brucella","Brucella IgM/IgG","Infectious Disease"],["rickettsial","Rickettsial Serology","Infectious Disease"],["scrub-typhus","Scrub Typhus IgM","Infectious Disease"],["cmv-pcr","CMV PCR","Infectious Disease"],["ebv-pcr","EBV PCR","Infectious Disease"],["hiv-vl","HIV Viral Load","Infectious Disease"],
  ["cdiff-gdh","C. difficile GDH Antigen","Gastroenterology / Stool"],["cdiff-toxin-ab","C. difficile Toxin A & B","Gastroenterology / Stool"],["cdiff-combo","C. difficile GDH + Toxin A/B","Gastroenterology / Stool"],["cdiff-naat","C. difficile NAAT / PCR","Gastroenterology / Microbiology"],["hp-stool","H. pylori Stool Antigen","Gastroenterology / Stool"],["hp-urea","H. pylori Urea Breath Test","Gastroenterology"],["fecal-calprotectin-q","Fecal Calprotectin Quantitative","Gastroenterology / Stool"],["fecal-lactoferrin","Fecal Lactoferrin","Gastroenterology / Stool"],["fecal-elastase","Fecal Pancreatic Elastase","Gastroenterology / Stool"],["fecal-alpha1","Fecal Alpha-1 Antitrypsin","Gastroenterology / Stool"],["gi-pathogen-pcr","GI Pathogen PCR Panel","Gastroenterology / Microbiology"],["gi-parasite-pcr","GI Parasite PCR Panel","Gastroenterology / Microbiology"],["celiac-panel","Celiac Disease Panel","Gastroenterology / Immunology"],["gastrin","Serum Gastrin","Gastroenterology"],["chromogranin-a","Chromogranin A","Gastroenterology / Oncology"],["ca19-9","CA 19-9","Gastroenterology / Oncology"],
  ["hbv-dna","HBV DNA PCR / Viral Load","Hepatology"],["hcv-rna","HCV RNA PCR / Viral Load","Hepatology"],["hcv-genotype","HCV Genotype","Hepatology"],["hepatitis-a-igm","Hepatitis A IgM","Hepatology"],["hepatitis-e-igm","Hepatitis E IgM","Hepatology"],["afp","AFP","Hepatology / Oncology"],["ceruloplasmin","Ceruloplasmin","Hepatology"],["urine-copper","24-Hour Urine Copper","Hepatology"],["ama","Anti-Mitochondrial Antibody (AMA)","Hepatology / Autoimmune"],["asma","Anti-Smooth Muscle Antibody (ASMA)","Hepatology / Autoimmune"],["anti-lkm1","Anti-LKM-1","Hepatology / Autoimmune"],["ig-g4","IgG4","Hepatology / Immunology"],["fibrotest","FibroTest / FibroSure","Hepatology"],
  ["ana-ifa","ANA by IFA","Rheumatology"],["anti-ccp","Anti-CCP","Rheumatology"],["dsdna","Anti-dsDNA","Rheumatology"],["ena-profile","ENA Profile","Rheumatology / Autoimmune"],["anca","ANCA Profile","Rheumatology"],["c3-c4","Complement C3/C4","Rheumatology"],["ch50","CH50","Rheumatology / Immunology"],["hla-b27","HLA-B27","Rheumatology"],["myositis-panel","Myositis Antibody Panel","Rheumatology"],["aps-panel","Antiphospholipid Syndrome Panel","Rheumatology"],
  ["csf-meningitis","CSF Meningitis/Encephalitis PCR Panel","Neurology / CSF"],["csf-oligoclonal","CSF Oligoclonal Bands","Neurology / CSF"],["csf-igg-index","CSF IgG Index","Neurology / CSF"],["aqp4","AQP4/NMO-IgG","Neurology"],["mog","MOG-IgG","Neurology"],["nmda","NMDA Receptor Antibody","Neurology"],["lgi1","LGI1 Antibody","Neurology"],["caspr2","CASPR2 Antibody","Neurology"],["achr","AChR Antibody","Neurology"],["musk","MuSK Antibody","Neurology"],
  ["amh","Anti-Müllerian Hormone (AMH)","Gynecology / Fertility"],["inhibin-b","Inhibin B","Gynecology / Fertility"],["hpv-genotype","High-Risk HPV Genotyping","Gynecology / Molecular"],["chlamydia-gono","Chlamydia / Gonorrhea NAAT","Gynecology / Microbiology"],["group-b-strep","Group B Streptococcus Screen","Obstetrics"],["preeclampsia-panel","Preeclampsia Biomarker Panel","Obstetrics"],
  ["total-ige","Total IgE","Allergy / Immunology"],["specific-ige","Specific IgE Allergy Panel","Allergy / Immunology"],["immunoglobulins","IgG / IgA / IgM","Immunology"],["igg-subclasses","IgG Subclasses","Immunology"],["serum-free-light","Serum Free Light Chains","Oncology"],["immunofixation","Serum Immunofixation","Oncology"],["flow-cytometry","Flow Cytometry","Hematology / Oncology"],["ihc","Immunohistochemistry (IHC)","Histopathology"],["molecular-ngs","Molecular / NGS Panel","Molecular Pathology"]
].map(([id,name,category]) => lab(id,name,category));

const EXTRA_IMAGING: DiagnosticCatalogItem[] = [
  ["xray-chest-pa","Chest X-ray PA","X-ray"],["xray-chest-ap","Chest X-ray AP / Portable","X-ray"],["xray-abdomen","Abdominal X-ray Erect / Supine","X-ray"],["xray-kub","KUB X-ray","X-ray"],["xray-cspine","Cervical Spine X-ray","X-ray"],["xray-tspine","Thoracic Spine X-ray","X-ray"],["xray-lspine","Lumbar Spine X-ray","X-ray"],["xray-pelvis","Pelvis X-ray","X-ray"],["xray-shoulder","Shoulder X-ray","X-ray"],["xray-knee","Knee X-ray","X-ray"],["xray-hip","Hip X-ray","X-ray"],["xray-hand","Hand / Wrist X-ray","X-ray"],["xray-foot","Foot / Ankle X-ray","X-ray"],["mammography","Mammography","Breast Imaging"],
  ["usg-whole-abdomen","USG Whole Abdomen","Ultrasound"],["usg-abdomen-pelvis","USG Abdomen & Pelvis","Ultrasound"],["usg-kub","USG KUB","Ultrasound"],["usg-liver-hbs","USG Liver / Hepatobiliary System","Ultrasound"],["usg-pancreas","USG Pancreas","Ultrasound"],["usg-thyroid","USG Thyroid","Ultrasound"],["usg-neck","USG Neck / Salivary Glands","Ultrasound"],["usg-breast","USG Breast","Ultrasound"],["usg-scrotum","USG Scrotum / Testes","Ultrasound"],["usg-small-parts","USG Small Parts / Soft Tissue","Ultrasound"],["usg-transvaginal","Transvaginal Ultrasound","Gynecologic Imaging"],["usg-obstetric","Obstetric Ultrasound","Obstetric Imaging"],["usg-nt","NT / NB Scan","Obstetric Imaging"],["usg-level2","Level II / Anomaly Scan","Obstetric Imaging"],["usg-growth","Obstetric Growth Scan","Obstetric Imaging"],["usg-fetal-doppler","Fetal Colour Doppler","Obstetric Imaging"],["usg-carotid-doppler","Carotid Doppler","Doppler"],["usg-venous-doppler","Venous Doppler Lower Limb","Doppler"],["usg-arterial-doppler","Arterial Doppler Lower Limb","Doppler"],["usg-portal-doppler","Portal Vein Doppler","Doppler"],["usg-renal-doppler","Renal Artery Doppler","Doppler"],["fibroscan","FibroScan / Liver Elastography","Elastography"],
  ["ct-head","CT Head / Brain","CT"],["ct-chest","CT Chest","CT"],["ct-abdomen","CT Abdomen & Pelvis","CT"],["ct-kub","CT KUB","CT"],["hrct-chest","HRCT Chest","CT"],["ct-pns","CT PNS","CT"],["ct-spine","CT Spine","CT"],["ct-triple-phase-liver","Triple Phase CT Liver","CT"],["ct-enterography","CT Enterography","CT"],["ct-colonography","CT Colonography","CT"],["ct-urography","CT Urography","CT"],["cta-brain","CT Cerebral Angiography","CT Angiography"],["cta-coronary","CT Coronary Angiography","CT Angiography"],["cta-pulmonary","CT Pulmonary Angiography","CT Angiography"],["cta-aorta","CT Aortogram","CT Angiography"],["ct-perfusion","CT Brain Perfusion","CT"],["ct-polytrauma","CT Polytrauma","CT"],["ct-guided-procedure","CT-Guided Biopsy / Drainage","Interventional Radiology"],
  ["mri-brain","MRI Brain","MRI"],["mri-brain-contrast","MRI Brain with Contrast","MRI"],["mri-stroke","MRI Stroke Protocol","MRI"],["mri-epilepsy","MRI Epilepsy Protocol","MRI"],["mri-pituitary","MRI Pituitary","MRI"],["mri-orbit","MRI Orbit","MRI"],["mri-iac","MRI Internal Auditory Canal","MRI"],["mri-cervical","MRI Cervical Spine","MRI"],["mri-thoracic","MRI Thoracic Spine","MRI"],["mri-lumbar","MRI Lumbar Spine","MRI"],["mri-whole-spine","MRI Whole Spine","MRI"],["mri-knee","MRI Knee","MSK MRI"],["mri-shoulder","MRI Shoulder","MSK MRI"],["mri-hip","MRI Hip","MSK MRI"],["mri-ankle","MRI Ankle / Foot","MSK MRI"],["mri-pelvis","MRI Pelvis","MRI"],["mri-prostate","Multiparametric MRI Prostate","MRI"],["mri-liver","MRI Liver","MRI"],["mrcp","MRCP","MRI"],["mri-enterography","MR Enterography","MRI"],["mri-breast","MRI Breast","Breast Imaging"],["mri-cardiac","Cardiac MRI","Cardiac Imaging"],["mra-brain","MRA Brain","MRA / MRV"],["mrv-brain","MRV Brain","MRA / MRV"],["mra-neck","MRA Neck / Carotids","MRA / MRV"],["mri-perfusion","MRI Brain Perfusion","MRI"],["mri-spectroscopy","MR Spectroscopy","MRI"],["mri-dti","Diffusion Tensor Imaging (DTI)","MRI"],
  ["pet-ct","PET-CT","Nuclear Medicine"],["fdg-pet-ct","FDG PET-CT","Nuclear Medicine"],["psma-pet-ct","PSMA PET-CT","Nuclear Medicine"],["dotatate-pet-ct","DOTATATE PET-CT","Nuclear Medicine"],["bone-scan","Whole Body Bone Scan","Nuclear Medicine"],["spect-ct","SPECT-CT","Nuclear Medicine"],["hida-scan","HIDA Scan","Nuclear Medicine"],["dmsa-scan","DMSA Renal Scan","Nuclear Medicine"],
  ["echo-2d","2D Echocardiography","Cardiac Imaging"],["echo-3d","3D Echocardiography","Cardiac Imaging"],["stress-echo","Stress Echocardiography","Cardiac Imaging"],["tee","Transesophageal Echocardiography","Cardiac Imaging"],["ecg","ECG / EKG","Cardiac Diagnostics"],["holter","Holter Monitoring","Cardiac Diagnostics"],["tmt","Treadmill Test (TMT)","Cardiac Diagnostics"],["dsa","Digital Subtraction Angiography (DSA)","Interventional Radiology"],["barium-swallow","Barium Swallow","Fluoroscopy"],["barium-meal","Barium Meal Follow Through","Fluoroscopy"],["barium-enema","Barium Enema","Fluoroscopy"],["hsg","Hysterosalpingography (HSG)","Fluoroscopy"],["mcu","MCU / VCUG","Fluoroscopy"],["endoscopy","Upper GI Endoscopy","Endoscopy"],["colonoscopy","Colonoscopy","Endoscopy"],["ercp","ERCP","Endoscopy"],["eus","Endoscopic Ultrasound (EUS)","Endoscopy"],["bronchoscopy","Bronchoscopy","Endoscopy"],["cystoscopy","Cystoscopy","Endoscopy"],["eeG","EEG","Neurodiagnostics"],["emg-ncs","EMG / NCS","Neurodiagnostics"],["sleep-study","Polysomnography / Sleep Study","Sleep Diagnostics"],["spirometry","Spirometry","Pulmonary Diagnostics"],["pft","Pulmonary Function Test","Pulmonary Diagnostics"]
].map(([id,name,modality,category]) => imaging(id,name,modality,category));

const unique = (items: DiagnosticCatalogItem[]) => Array.from(new Map(items.map((x) => [x.id, x])).values()).sort((a,b) => a.name.localeCompare(b.name));

export const LAB_CATALOG = unique([...BASE_LABS, ...EXTRA_LABS]);
export const RADIOLOGY_CATALOG = unique([...BASE_RADIOLOGY, ...EXTRA_IMAGING]);
export const DIAGNOSTIC_CATALOG = unique([...LAB_CATALOG, ...RADIOLOGY_CATALOG]);
