"use client";

import Link from "next/link";
import { useState } from "react";

export default function NewFacilityPage() {
  const [form, setForm] = useState({name:"",facilityType:"HOSPITAL",subscriptionModel:"BOTH",ownerName:"",doctorInCharge:"",licenseNumber:"",registrationNumber:"",address:"",city:"",state:"",pincode:"",phone:"",email:"",telegramToken:"",telegramChatId:""});
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [done,setDone]=useState<any>(null);
  const change=(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm(f=>({...f,[e.target.name]:e.target.value}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/owner/facilities",{method:"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not create facility");setDone(j.facility)}catch(e){setError(e instanceof Error?e.message:"Could not create facility")}finally{setBusy(false)}};
  if(done)return <main className="min-h-screen bg-[#f6f7fb] p-6 text-slate-900"><div className="mx-auto max-w-2xl rounded-2xl border border-emerald-200 bg-white p-6"><p className="text-sm font-medium text-emerald-700">Facility created</p><h1 className="mt-1 text-2xl font-semibold">{done.name}</h1><p className="mt-3 text-sm">Products: {done.subscriptionModel}</p><p className="mt-1 text-sm">Telegram: {done.telegram ? "Connected" : "Not configured"}</p><Link className="mt-6 inline-block rounded-xl bg-[#c2183a] px-4 py-3 text-sm font-semibold text-white" href="/owner/hospitals">Back to Hospitals</Link></div></main>;
  const field=(n:string,l:string,req=true)=><label className="block"><span className="text-sm font-medium">{l}{req?" *":""}</span><input name={n} value={(form as any)[n]} onChange={change} required={req} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3"/></label>;
  return <main className="min-h-screen bg-[#f6f7fb] p-4 text-slate-900 sm:p-6"><div className="mx-auto max-w-4xl"><Link href="/owner/hospitals" className="text-sm text-[#c2183a]">← Hospitals</Link><h1 className="mt-4 text-2xl font-semibold">Add facility</h1><p className="mt-1 text-sm text-slate-500">Create an OPD/IPD workspace and optionally connect Telegram.</p>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<form onSubmit={submit} className="mt-6 space-y-5">
<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Facility</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("name","Facility name")}<label><span className="text-sm font-medium">Type *</span><select name="facilityType" value={form.facilityType} onChange={change} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3"><option value="HOSPITAL">Hospital</option><option value="CLINIC">Clinic</option></select></label><label><span className="text-sm font-medium">Products *</span><select name="subscriptionModel" value={form.subscriptionModel} onChange={change} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3"><option value="BOTH">OPD + IPD</option><option value="OPD">OPD only</option><option value="IPD">IPD only</option></select></label>{field("ownerName","Facility owner")}{field("doctorInCharge","Doctor in charge")}{field("licenseNumber","License number",false)}{field("registrationNumber","Registration number",false)}</div></section>
<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Address & contact</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("address","Address")}{field("city","City")}{field("state","State")}{field("pincode","Pincode")}{field("phone","Phone",false)}{field("email","Email",false)}</div></section>
<section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Telegram</h2><p className="mt-1 text-xs text-slate-500">Bot tokens are verified with Telegram and encrypted before storage.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("telegramToken","Bot token",false)}{field("telegramChatId","Notification chat ID",false)}</div></section>
<button disabled={busy} className="w-full rounded-xl bg-[#c2183a] px-4 py-3 font-semibold text-white disabled:opacity-50">{busy?"Creating and verifying…":"Create facility"}</button></form></div></main>;
}