import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { Prisma } from "@prisma/client";

async function getContext(){const session=await getSession();if(!session)return null;const membership=await prisma.clinicMember.findFirst({where:{doctorId:session.doctorId},orderBy:{createdAt:"asc"}});if(!membership)return null;return{session,clinicId:membership.clinicId};}
import { getSession } from "@/lib/session";
const statuses=["Open","In Treatment","Observation","Admitted","Discharged","Transferred"];
const triage=["Resuscitation","Emergency","Urgent","Less Urgent","Non-Urgent"];
const CLINICAL_MARKER="__MEDLUM_EMERGENCY_CLINICAL__";
function clinicalNotes(raw:string){try{const x=JSON.parse(raw||"{}");if(x?.marker===CLINICAL_MARKER)return x;return{marker:CLINICAL_MARKER,freeText:raw||""}}catch{return{marker:CLINICAL_MARKER,freeText:raw||""}}}
async function listCases(clinicId:string){return prisma.$queryRaw<any[]>(Prisma.sql`SELECT e.*,p."name" AS "patientName",p."phone" AS "patientPhone",d."name" AS "doctorName" FROM "EmergencyCase" e LEFT JOIN "Patient" p ON p."id"=e."patientId" LEFT JOIN "Doctor" d ON d."id"=e."doctorId" WHERE e."clinicId"=${clinicId} ORDER BY e."arrivalTime" DESC LIMIT 200`);}
export async function GET(){const ctx=await getContext();if(!ctx)return NextResponse.json({error:"Unauthorized"},{status:401});const rows=await listCases(ctx.clinicId);const cases=rows.map(c=>{const clinical=clinicalNotes(c.notes);return{...c,clinical,patient:c.patientId?{id:c.patientId,name:c.patientName,phone:c.patientPhone}:null,doctor:{id:c.doctorId,name:c.doctorName}}});return NextResponse.json({cases},{headers:{"Cache-Control":"no-store"}})}
export async function POST(req:Request){const ctx=await getContext();if(!ctx)return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await req.json();const patientId=body.patientId?String(body.patientId):null;if(patientId){const patient=await prisma.patient.findFirst({where:{id:patientId,clinicId:ctx.clinicId}});if(!patient)return NextResponse.json({success:false,error:"Patient not found in this clinic."},{status:404});}const arrivalMode=["Ambulance","Walk-in","Referral"].includes(String(body.arrivalMode))?String(body.arrivalMode):"Walk-in";const level=triage.includes(String(body.triageLevel))?String(body.triageLevel):"Urgent";const id=crypto.randomUUID();const arrivalTime=body.arrivalTime?new Date(body.arrivalTime):new Date();const vitals=typeof body.vitals==="string"?body.vitals:JSON.stringify(body.vitals||{});const notes=JSON.stringify({marker:CLINICAL_MARKER,mlcNumber:String(body.mlcNumber||"").trim(),diagnosis:String(body.diagnosis||"").trim(),hpi:String(body.hpi||"").trim(),pastHistory:String(body.pastHistory||"").trim(),surgicalHistory:String(body.surgicalHistory||"").trim(),systemicExam:String(body.systemicExam||"").trim(),workingDiagnosis:String(body.workingDiagnosis||"").trim(),freeText:String(body.notes||"").trim()});await prisma.$executeRaw(Prisma.sql`INSERT INTO "EmergencyCase" ("id","clinicId","patientId","doctorId","arrivalMode","ambulanceProvider","ambulanceNumber","arrivalTime","triageLevel","chiefComplaint","vitals","allergies","status","disposition","notes","createdAt","updatedAt") VALUES (${id},${ctx.clinicId},${patientId},${ctx.session.doctorId},${arrivalMode},${String(body.ambulanceProvider||"").trim()},${String(body.ambulanceNumber||"").trim()},${arrivalTime},${level},${String(body.chiefComplaint||"").trim()},${vitals},${String(body.allergies||"").trim()},'Open','',${notes},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`);await prisma.auditLog.create({data:{doctorId:ctx.session.doctorId,action:"EMERGENCY_CASE_CREATED",entity:"EmergencyCase",entityId:id,meta:JSON.stringify({clinicId:ctx.clinicId,patientId,triageLevel:level,arrivalMode,mlcNumber:String(body.mlcNumber||"").trim()})}});return NextResponse.json({success:true,id});}catch(e){console.error("emergency post",e);return NextResponse.json({success:false,error:"Server error"},{status:500});}}
export async function PATCH(req:Request){const ctx=await getContext();if(!ctx)return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await req.json(),id=String(body.id||"");if(!id)return NextResponse.json({success:false,error:"Case id is required."},{status:400});const rows=await prisma.$queryRaw<any[]>(Prisma.sql`SELECT * FROM "EmergencyCase" WHERE "id"=${id} AND "clinicId"=${ctx.clinicId} LIMIT 1`),existing=rows[0];if(!existing)return NextResponse.json({success:false,error:"Emergency case not found."},{status:404});const status=statuses.includes(String(body.status))?String(body.status):existing.status,level=triage.includes(String(body.triageLevel))?String(body.triageLevel):existing.triageLevel,disposition=body.disposition===undefined?existing.disposition:String(body.disposition),oldClinical=clinicalNotes(existing.notes),clinical={...oldClinical,...(body.clinical||{})},notes=JSON.stringify(clinical),ambulanceProvider=body.ambulanceProvider===undefined?existing.ambulanceProvider:String(body.ambulanceProvider),ambulanceNumber=body.ambulanceNumber===undefined?existing.ambulanceNumber:String(body.ambulanceNumber),vitals=body.vitals===undefined?existing.vitals:(typeof body.vitals==="string"?body.vitals:JSON.stringify(body.vitals||{})),allergies=body.allergies===undefined?existing.allergies:String(body.allergies);await prisma.$executeRaw(Prisma.sql`UPDATE "EmergencyCase" SET "status"=${status},"triageLevel"=${level},"disposition"=${disposition},"notes"=${notes},"ambulanceProvider"=${ambulanceProvider},"ambulanceNumber"=${ambulanceNumber},"vitals"=${vitals},"allergies"=${allergies},"closedAt"=${["Discharged","Transferred"].includes(status)?(existing.closedAt||new Date()):null},"updatedAt"=CURRENT_TIMESTAMP WHERE "id"=${id} AND "clinicId"=${ctx.clinicId}`);await prisma.auditLog.create({data:{doctorId:ctx.session.doctorId,action:"EMERGENCY_CASE_UPDATED",entity:"EmergencyCase",entityId:id,meta:JSON.stringify({clinicId:ctx.clinicId,status,triageLevel:level})}});return NextResponse.json({success:true,id});}catch(e){console.error("emergency patch",e);return NextResponse.json({success:false,error:e instanceof Error?e.message:"Server error"},{status:500});}}
