"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/AppShell";
import { useDoctor } from "@/components/DoctorProvider";

export default function IPDCensusPage(){
 const{doctor,loading:authLoading}=useDoctor(); const[patients,setPatients]=useState<any[]>([]); const[rooms,setRooms]=useState<any[]>([]); const[loading,setLoading]=useState(true); const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/ipd",{credentials:"include",cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Could not load IPD census");setPatients(d.patients||[]);setRooms(d.rooms||[])}catch(e:any){setError(e.message||"Could not load IPD census")}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!authLoading&&doctor)void load()},[authLoading,doctor,load]);
 if(authLoading||!doctor)return <div className="min-h-screen flex items-center justify-center bg-[#140a1f] text-white text-sm">Loading...</div>;
 return <AppShell><div className="p-4 space-y-3"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">IPD</h2><p className="text-xs text-gray-500">Active admissions · beds · clinical workspace</p></div><Link href="/patients" className="h-9 px-3 rounded-lg border text-xs inline-flex items-center">Open Patients</Link></div>{error&&<div className="bg-red-50 text-red-700 px-3 py-2 rounded-lg text-sm">{error}</div>}<div className="grid lg:grid-cols-[1fr_320px] gap-3"><section className="bg-white rounded-xl border shadow-sm overflow-hidden"><div className="px-3 py-3 border-b flex items-center justify-between"><h3 className="font-semibold text-sm">IPD Census</h3><span className="text-[10px] text-gray-500">{patients.length} active admission{patients.length===1?"":"s"}</span></div>{loading?<div className="p-6 text-center text-sm text-gray-400">Loading…</div>:patients.length===0?<div className="p-6 text-center text-sm text-gray-500">No active IPD patients.</div>:<div className="divide-y">{patients.map((p:any)=><Link key={p.id} href={`/ipd/${p.id}`} className="block px-3 py-3 hover:bg-gray-50"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="font-semibold text-sm truncate">{p.name}</p><p className="text-[11px] text-gray-500">{p.age} yrs · {p.gender} · {p.wardType||"Ward"} · Bed {p.roomNumber||"Unassigned"}</p><p className="text-[10px] text-gray-400 mt-0.5">Admission: {p.admissionDate?new Date(p.admissionDate).toLocaleString("en-IN"):"—"}</p></div><div className="text-right text-[11px] shrink-0">{p.consultantName&&<p className="font-medium">{p.consultantName}</p>}{p.vitals&&<p>BP {p.vitals.bp||"—"} · P {p.vitals.pulse||"—"} · SpO₂ {p.vitals.spo2||"—"} · RR {p.vitals.rr||"—"}</p>}</div></div><div className="mt-2 flex flex-wrap gap-1.5">{p.allergies&&<span className="px-2 py-1 rounded-full bg-red-50 text-red-700 text-[10px]">⚠ Allergy: {p.allergies}</span>}{p.workingDiagnosis&&<span className="px-2 py-1 rounded-full bg-gray-100 text-gray-700 text-[10px]">Dx: {p.workingDiagnosis}</span>}<span className="px-2 py-1 rounded-full bg-[#f6f4f8] text-gray-600 text-[10px]">Open clinical workspace →</span></div></Link>)}</div>}</section><section className="bg-white rounded-xl border shadow-sm p-3"><h3 className="font-semibold text-sm mb-2">Beds</h3><div className="space-y-2 max-h-[560px] overflow-auto">{rooms.map((r:any)=><div key={r.id} className="border rounded-lg p-2.5 flex justify-between"><div><p className="font-medium text-sm">Bed {r.roomNumber}</p><p className="text-[11px] text-gray-500">{r.roomCategory} · {r.unitType}</p></div><span className="text-[10px] px-2 py-1 rounded-full h-fit">{r.occupied?"Occupied":"Available"}</span></div>)}</div></section></div></div></AppShell>;
}