"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useDoctor } from "@/components/DoctorProvider";

type Hospital={id:string;name:string;doctors:number;patients:number;invoices:number;activeIpd:number;collectedRevenue:number};
type Data={hospitals:Hospital[];platform:{activeHospitals:number;activeDoctors:number;totalPatients:number;collectedClinicalRevenue:number;collectedThisMonth:number}};
const money=(v:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);

export default function OwnerHospitalsPage(){
 const {doctor,loading}=useDoctor(); const [data,setData]=useState<Data|null>(null); const [error,setError]=useState("");
 useEffect(()=>{if(!doctor?.isOwner&&doctor?.primaryRole!=="Owner")return;fetch("/api/owner/overview",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load hospitals");return d}).then(setData).catch(e=>setError(e instanceof Error?e.message:"Unable to load hospitals"));},[doctor]);
 if(loading)return <div className="min-h-screen grid place-items-center bg-[#f6f7fb] text-sm text-slate-500">Loading…</div>;
 if(!doctor)return <div className="min-h-screen grid place-items-center bg-[#f6f7fb]"><Link href="/login" className="text-[#c2183a]">Sign in</Link></div>;
 if(!doctor.isOwner&&doctor.primaryRole!=="Owner")return <div className="min-h-screen grid place-items-center bg-[#f6f7fb]"><Link href="/dashboard" className="text-[#c2183a]">Open clinical workspace</Link></div>;
 const selectedId=new URLSearchParams(typeof window!=="undefined"?window.location.search:"").get("id"); const selected=data?.hospitals.find(h=>h.id===selectedId);
 return <div className="min-h-screen bg-[#f6f7fb] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><div><Link href="/owner" className="text-lg font-bold">MedLum</Link><p className="text-xs text-slate-500">Owner → Hospitals</p></div><Link href="/owner" className="text-sm font-medium text-[#c2183a]">← Dashboard</Link></div></header>
 <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6">{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold">Hospitals</h1><p className="mt-1 text-sm text-slate-500">Facilities running the first MedLum product: OPD and IPD.</p></div><div className="flex items-center gap-4"><div className="text-sm text-slate-500">{data?.platform.activeHospitals??0} active · {data?.platform.activeDoctors??0} doctors</div><Link href="/owner/hospitals/new" className="rounded-xl bg-[#c2183a] px-4 py-3 text-sm font-semibold text-white">+ Add facility</Link></div></div>
 {selected&&<div className="mt-5 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wide text-slate-400">Selected hospital</p><h2 className="mt-1 text-xl font-semibold">{selected.name}</h2></div><Link href="/owner/hospitals" className="text-sm text-slate-500">Clear</Link></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Doctors",selected.doctors],["Patients",selected.patients],["IPD",selected.activeIpd],["Invoices",selected.invoices],["Collected",money(selected.collectedRevenue)]].map(([k,v])=><div key={String(k)} className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{k}</p><p className="mt-1 text-lg font-semibold">{v}</p></div>)}</div></div>}
 <div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="grid grid-cols-[1fr_auto] gap-4 border-b border-slate-100 px-5 py-4 text-xs font-semibold uppercase tracking-wide text-slate-400 sm:grid-cols-[1.5fr_0.7fr_0.7fr_0.7fr_1fr]"><span>Hospital</span><span>Doctors</span><span>Patients</span><span>IPD</span><span>Collected</span></div>{(data?.hospitals??[]).map(h=><Link key={h.id} href={`/owner/hospitals?id=${encodeURIComponent(h.id)}`} className="grid grid-cols-[1fr_auto] gap-4 border-b border-slate-100 px-5 py-4 text-sm hover:bg-slate-50 sm:grid-cols-[1.5fr_0.7fr_0.7fr_0.7fr_1fr]"><div><p className="font-medium">{h.name}</p><p className="mt-1 text-xs text-slate-400">Active facility</p></div><span>{h.doctors}</span><span>{h.patients}</span><span>{h.activeIpd}</span><span>{money(h.collectedRevenue)}</span></Link>)}{!data?.hospitals.length&&<div className="p-10 text-center text-sm text-slate-500">No hospitals are connected yet.</div>}</div>
 <p className="mt-6 text-xs leading-5 text-slate-400">This owner view is intentionally separate from clinical work. Hospital staff use the OPD/IPD workspace; the platform owner sees adoption, activity and recorded billing here.</p></main></div>;
}
