"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import AppShell from "@/components/AppShell";

export default function ReportsPage(){
  const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [days,setDays]=useState(30);
  async function load(){try{setError("");const r=await fetch(`/api/reports?days=${days}`,{credentials:"include",cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not load reports");setData(j)}catch(e){setError(e instanceof Error?e.message:"Could not load reports")}}
  useEffect(()=>{load()},[days]);
  const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}`;
  const maxTrend=useMemo(()=>Math.max(1,...(data?.trend||[]).map((x:any)=>Math.max(x.billed,x.collected,x.patients*1000))),[data]);
  if(!data&&!error)return <AppShell><p className="text-sm text-gray-500">Loading reports…</p></AppShell>;
  if(error)return <AppShell><Link href="/dashboard" className="text-xs text-[#c2183a]">← Dashboard</Link><div className="mt-4 rounded-xl border bg-white p-4 text-sm text-red-600">{error}</div></AppShell>;
  return <AppShell><div className="mb-4 flex items-start justify-between gap-3"><div><Link href="/dashboard" className="text-xs text-[#c2183a]">← Dashboard</Link><h1 className="mt-1 text-xl font-semibold">Reports & Analytics</h1><p className="text-xs text-gray-500">Clinic-wide operational, revenue and insurance intelligence.</p></div><select value={days} onChange={e=>setDays(Number(e.target.value))} className="h-9 border rounded-lg px-2 text-xs bg-white"><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div>
    <div className="grid grid-cols-2 gap-2 mb-4">{[["Patients",data.counts.patients,data.periodCounts.patients+" new"],["Encounters",data.counts.encounters,data.periodCounts.encounters+" recent"],["Appointments",data.counts.appointments,data.periodCounts.appointments+" recent"],["Invoices",data.counts.invoices,data.periodCounts.invoices+" recent"],["Lab orders",data.counts.labOrders,"all time"],["Diagnostics",data.counts.diagnosticOrders,"all time"],["Prescriptions",data.counts.prescriptions,"all time"],["Claims",data.counts.claims,"all time"]].map(([k,v,s])=><div key={k as string} className="bg-white rounded-xl border p-3"><div className="text-[11px] text-gray-500">{k}</div><div className="text-xl font-bold">{v}</div><div className="text-[10px] text-gray-400">{s}</div></div>)}</div>
    <div className="bg-white rounded-xl border p-4 mb-3"><div className="flex justify-between items-center mb-3"><h2 className="font-semibold text-sm">Revenue</h2><span className="text-[11px] text-gray-500">{Math.round(data.revenue.collectionRate*100)}% collected</span></div><div className="grid grid-cols-3 gap-2"><div><div className="text-[11px] text-gray-500">Billed</div><div className="font-bold">{money(data.revenue.billed)}</div></div><div><div className="text-[11px] text-gray-500">Collected</div><div className="font-bold">{money(data.revenue.collected)}</div></div><div><div className="text-[11px] text-gray-500">Outstanding</div><div className="font-bold">{money(data.revenue.outstanding)}</div></div></div><div className="mt-3 text-xs text-gray-500">Selected period: {money(data.revenue.periodBilled)} billed · {money(data.revenue.periodCollected)} collected</div></div>
    <div className="bg-white rounded-xl border p-4 mb-3"><h2 className="font-semibold text-sm mb-2">Daily activity & cash trend</h2><div className="overflow-x-auto"><div className="min-w-[520px] space-y-1">{data.trend.map((x:any)=><div key={x.date} className="grid grid-cols-[65px_1fr_1fr_55px] gap-2 items-center text-[10px]"><span className="text-gray-500">{x.date.slice(5)}</span><div className="h-2 bg-gray-100 rounded"><div className="h-2 bg-[#c2183a] rounded" style={{width:`${Math.min(100,x.billed/maxTrend*100)}%`}}/></div><div className="h-2 bg-gray-100 rounded"><div className="h-2 bg-green-500 rounded" style={{width:`${Math.min(100,x.collected/maxTrend*100)}%`}}/></div><span className="text-gray-500">{x.encounters} enc.</span></div>)}</div></div><div className="mt-2 text-[10px] text-gray-400">Bars: billed / collected · encounters shown at right.</div></div>
    <div className="bg-white rounded-xl border p-4 mb-3"><h2 className="font-semibold text-sm mb-2">Consultant performance</h2>{data.consultants.map((x:any)=><div key={x.doctorId} className="flex justify-between gap-3 py-2 border-b last:border-0 text-sm"><div><div className="font-medium">{x.name}</div><div className="text-[10px] text-gray-500">{x.invoices} invoices · billed {money(x.billed)}</div></div><span className="font-semibold">{money(x.collected)}</span></div>)}{!data.consultants.length&&<p className="text-xs text-gray-400">No consultant activity yet.</p>}</div>
    <div className="grid grid-cols-1 gap-3 md:grid-cols-2"><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Payment methods</h2>{Object.entries(data.paymentMethods).map(([k,v]:any)=><div key={k} className="flex justify-between py-2 border-b last:border-0 text-sm"><span>{k}</span><span className="font-semibold">{money(v)}</span></div>)}</div><div className="bg-white rounded-xl border p-4"><h2 className="font-semibold text-sm mb-2">Appointments ({days}d)</h2>{Object.entries(data.appointmentStatuses).map(([k,v]:any)=><div key={k} className="flex justify-between py-2 border-b last:border-0 text-sm"><span>{k}</span><span className="font-semibold">{v}</span></div>)}</div></div>
    <div className="bg-white rounded-xl border p-4 mt-3"><h2 className="font-semibold text-sm mb-2">Insurance performance</h2><div className="grid grid-cols-3 gap-2 mb-2"><div><div className="text-[11px] text-gray-500">Requested</div><div className="font-bold">{money(data.insurance.requested)}</div></div><div><div className="text-[11px] text-gray-500">Approved</div><div className="font-bold">{money(data.insurance.approved)}</div></div><div><div className="text-[11px] text-gray-500">Settled</div><div className="font-bold">{money(data.insurance.settled)}</div></div></div>{Object.entries(data.insurance.byStatus).map(([k,v]:any)=><div key={k} className="flex justify-between py-2 border-b last:border-0 text-sm"><span>{k}</span><span className="font-semibold">{v}</span></div>)}</div>
  </AppShell>
}
